name: Update Readme

on:
  push:
  schedule:
    - cron: '0 0 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

permissions:
  packages: write
  contents: write

jobs:
  dotnet:
    name: Update Readme
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        persist-credentials: true
        lfs: true
        fetch-tags: true

    - name: Update Readme
      shell: pwsh
      run: ./.github/workflows/update-readme.ps1
      env:
        GH_TOKEN: ${{ github.token }}
    
    - name: Commit Changes
      run: |
        git config --global user.email "actions@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"

        git add ./profile/README.md
        git commit -m "[skip ci][bot] Update README.md"
        git push
